# Dockerfile.worker
FROM python:3.9-slim-buster

WORKDIR /app

# Install Nmap and necessary tools
RUN apt-get update && \
    apt-get install -y nmap sudo && \
    rm -rf /var/lib/apt/lists/* && \
    echo "worker ALL=(ALL) NOPASSWD: /usr/bin/nmap" >> /etc/sudoers

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY worker.py .

# Command to run the worker script
CMD ["python", "worker.py"]